-vhdl2008
${DSIM_HOME}/std_pkgs/src/ieee2008/std_logic_1164.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/std_logic_1164-body.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/std_logic_textio.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/ieee_std_context.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/math_real.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/math_real-body.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/numeric_bit.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/numeric_bit-body.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/ieee_bit_context.vhdl

#${DSIM_HOME}/std_pkgs/src/ieee2008/numeric_bit_unsigned.vhdl
#${DSIM_HOME}/std_pkgs/src/ieee2008/numeric_bit_unsigned-body.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/numeric_std.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/numeric_std-body.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/numeric_std_unsigned.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/numeric_std_unsigned-body.vhdl
#${DSIM_HOME}/std_pkgs/src/ieee2008/float_pkg.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/fixed_float_types.vhdl
#${DSIM_HOME}/std_pkgs/src/ieee2008/fixed_generic_pkg.vhdl
#${DSIM_HOME}/std_pkgs/src/ieee2008/fixed_generic_pkg-body.vhdl
#${DSIM_HOME}/std_pkgs/src/ieee2008/fixed_pkg.vhdl
#${DSIM_HOME}/std_pkgs/src/ieee2008/float_generic_pkg.vhdl
#${DSIM_HOME}/std_pkgs/src/ieee2008/float_generic_pkg-body.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/math_complex.vhdl
${DSIM_HOME}/std_pkgs/src/ieee2008/math_complex-body.vhdl
${DSIM_HOME}/std_pkgs/src/synopsys/std_logic_arith.vhdl
${DSIM_HOME}/std_pkgs/src/synopsys/std_logic_signed.vhdl
${DSIM_HOME}/std_pkgs/src/synopsys/std_logic_unsigned.vhdl
-f vital2000_f
